main:
  models_dir: models #Relative to the root of the repo
mlflow:
  tracking_uri: mlruns #Relative to the root of the repo, currently only a local path is supported as uri
transformers:
  seed: 8833
  pretrained_model: 'distilbert-base-uncased'