main:
  models_dir: models #Relative to the root of the repo
  fine_tuned_model_dir: saved_model
train:
  tune: False  # Hyperparameters
  fine_tune: True  # Pre-trained model
  test: True
fine_tuning:
  study_name: trials
  resume_previous: yes
  n_trials: 10
mlflow:
  tracking_uri: mlruns #Relative to the root of the repo, currently only a local path is supported as uri
transformers:
  seed: 8833
  pretrained_model: 'distilbert-base-uncased'
  epochs: 4
  batch_size: 256
  early_stopping_patience: 1